module.exports = {
  lastUpdate: '2020-02-25T19:08:10+08:00',
  author: 'DSRKafuU (https://dsrkafuu.su)',
  license: 'https://nga.178.com/read.php?tid=20339590',
  huntingData: {
    chocobo: {
      shadowbringers: [
        {
          server: '拉诺西亚',
          timeTable: ['09:00', '15:30', '22:00', ''],
          origin: '雷克兰德',
          route: '',
        },
        {
          server: '神意之地',
          timeTable: ['', '15:00', '22:00', ''],
          origin: '雷克兰德',
          route: '湖-岛-沙漠-妖精乡-森林-海',
        },
        {
          server: '萌芽池',
          timeTable: ['', '15:00', '22:00', ''],
          origin: '雷克兰德',
          route: '湖-岛-沙漠-妖精乡-森林-海',
        },
        {
          server: '幻影群岛',
          timeTable: ['', '', '21:00', '04:00'],
          origin: '黑风海',
          route: '海-森林-妖精乡-湖-沙漠-岛',
        },
        {
          server: '红玉海',
          timeTable: ['', '13:00', '20:00', '03:00'],
          origin: '雷克兰德',
          route: '湖-妖精乡-森林-沙漠-岛-海',
        },
        {
          server: '宇宙和音',
          timeTable: ['09:00', '16:00', '23:00', ''],
          origin: '雷克兰德',
          route: '湖-岛-沙漠-妖精乡-森林-海',
        },
        {
          server: '沃仙曦染',
          timeTable: ['10:00', '', '20:00', ''],
          origin: '雷克兰德',
          route: '湖-妖精乡-森林-沙漠-岛-海',
        },
        {
          server: '晨曦王座',
          timeTable: ['', '13:00', '22:00', ''],
          origin: '雷克兰德',
          route: '湖-岛-沙漠-妖精乡-森林-海',
        },
      ],
      stormblood: [
        {
          server: '拉诺西亚',
          timeTable: ['10:00', '16:30', '23:00', ''],
          origin: '',
          route: '',
        },
        {
          server: '神意之地',
          timeTable: ['', '11:30', '19:30', ''],
          origin: '红玉海',
          route: '海-草-延-边-山-湖',
        },
        {
          server: '萌芽池',
          timeTable: ['', '13:00', '19:30', ''],
          origin: '基拉巴尼亚边区',
          route: '边-山-湖-延-草-海',
        },
        {
          server: '幻影群岛',
          timeTable: ['', '', '', ''],
          origin: '',
          route: '',
        },
        {
          server: '红玉海',
          timeTable: ['', '12:30', '20:45', ''],
          origin: '延夏',
          route: '延-草-海-边-山-湖',
        },
        {
          server: '宇宙和音',
          timeTable: ['', '', '', ''],
          origin: '基拉巴尼亚边区',
          route: '边-山-湖-海-草-延',
        },
        {
          server: '沃仙曦染',
          timeTable: ['10:30', '', '20:30', ''],
          origin: '基拉巴尼亚边区',
          route: '边-山-湖-海-草-延',
        },
        {
          server: '晨曦王座',
          timeTable: ['10:00', '', '', ''],
          origin: '',
          route: '',
        },
      ],
    },
    moogle: {
      shadowbringers: [
        {
          server: '潮风亭',
          timeTable: ['', '13:00', '21:00', ''],
          origin: '雷克兰德',
          route: '',
        },
        {
          server: '白金幻象',
          timeTable: ['', '13:00', '19:30', '02:00'],
          origin: '黑风海',
          route: '',
        },
        {
          server: '白银乡',
          timeTable: ['', '', '21:00', ''],
          origin: '黑风海',
          route: '',
        },
        {
          server: '神拳痕',
          timeTable: ['09:00', '', '21:00', ''],
          origin: '雷克兰德',
          route: '',
        },
        {
          server: '旅人栈桥',
          timeTable: ['', '14:30', '21:30', ''],
          origin: '雷克兰德',
        },
        {
          server: '拂晓之间',
          timeTable: ['', '', '21:00', ''],
          origin: '雷克兰德',
          route: '',
        },
        {
          server: '龙巢神殿',
          timeTable: ['', '14:00', '22:00', ''],
          origin: '雷克兰德',
          route: '',
        },
        {
          server: '梦羽宝境',
          timeTable: ['', '', '18:50', ''],
          origin: '黑风海',
          route: '',
        },
      ],
      stormblood: [
        {
          server: '潮风亭',
          timeTable: ['', '', '', ''],
          origin: '',
          route: '',
        },
        {
          server: '白金幻象',
          timeTable: ['', '', '20:30', ''],
          origin: '基拉巴尼亚边区',
          route: '',
        },
        {
          server: '白银乡',
          timeTable: ['', '', '', ''],
          origin: '',
          route: '',
        },
        {
          server: '神拳痕',
          timeTable: ['', '', '22:00', ''],
          origin: '红玉海',
          route: '',
        },
        {
          server: '旅人栈桥',
          timeTable: ['', '', '20:30', ''],
          origin: '',
          route: '',
        },
        {
          server: '拂晓之间',
          timeTable: ['', '13:00', '', ''],
          origin: '基拉巴尼亚边区',
          route: '',
        },
        {
          server: '龙巢神殿',
          timeTable: ['', '', '20:00', ''],
          origin: '',
          route: '',
        },
        {
          server: '梦羽宝境',
          timeTable: ['', '', '22:30', ''],
          origin: '基拉巴尼亚边区',
          route: '',
        },
      ],
    },
    fatCat: {
      shadowbringers: [
        {
          server: '紫水栈桥',
          timeTable: ['', '14:00', '21:00', ''],
          origin: '雷克兰德',
          route: '湖-岛-沙漠-妖精乡-森林-海',
        },
        {
          server: '摩杜纳',
          timeTable: ['', '13:00', '20:00', ''],
          origin: '黑风海',
          route: '海-岛-沙漠-森林-妖精乡-湖',
        },
        {
          server: '静语庄园',
          timeTable: ['', '', '22:00', ''],
          origin: '雷克兰德',
          route: '湖-岛-沙漠-妖精乡-森林-海',
        },
        {
          server: '延夏',
          timeTable: ['', '12:30', '20:30', ''],
          origin: '雷克兰德',
          route: '湖-妖精乡-森林-沙漠-岛-海',
        },
        {
          server: '海猫茶屋',
          timeTable: ['', '13:30', '21:30', ''],
          origin: '雷克兰德',
          route: '湖-岛-沙漠-妖精乡-森林-海',
        },
        {
          server: '柔风海湾',
          timeTable: ['', '15:00', '22:00', ''],
          origin: '雷克兰德',
          route: '湖-岛-沙漠-妖精乡-森林-海',
        },
        {
          server: '琥珀原',
          timeTable: ['', '13:30', '21:00', '04:00'],
          origin: '雷克兰德',
          route: '湖-岛-沙漠-妖精乡-森林-海',
        },
      ],
      stormblood: [
        {
          server: '紫水栈桥',
          timeTable: ['', '', '', ''],
          origin: '',
          route: '',
        },
        {
          server: '摩杜纳',
          timeTable: ['', '', '21:00', ''],
          origin: '基拉巴尼亚边区',
          route: '边-山-湖-海-草-延',
        },
        {
          server: '静语庄园',
          timeTable: ['', '', '', ''],
          origin: '',
          route: '',
        },
        {
          server: '延夏',
          timeTable: ['', '14:30', '21:30', ''],
          origin: '基拉巴尼亚边区',
          route: '边-山-湖-海-草-延',
        },
        {
          server: '海猫茶屋',
          timeTable: ['', '', '', ''],
          origin: '延夏',
          route: '延-草-海-边-山-湖',
        },
        {
          server: '柔风海湾',
          timeTable: ['', '', '', ''],
          origin: '红玉海',
          route: '',
        },
        {
          server: '琥珀原',
          timeTable: ['', '13:00', '20:00', '03:00'],
          origin: '基拉巴尼亚边区',
          route: '边-山-湖-海-延-草',
        },
      ],
    },
  },
};
